# Generated by Django 5.1.4 on 2025-01-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Н', 'Низкий'), ('С', 'Средний'), ('В', 'Высокий')], default='H', max_length=7),
            preserve_default=False,
        ),
    ]
