# Generated by Django 5.1.4 on 2025-01-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0002_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Низкий', 'Н'), ('Средний', 'С'), ('Высокий', 'В')], max_length=7),
        ),
    ]
